runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app
service: flex-module

runtime_config:
  python_version: 2

resources:
  cpu: 0.1
  memory_gb: 0.9
  disk_size_gb: 10

manual_scaling:
  instances: 1

health_check:
  enable_health_check: False

env_variables:
  APP_ID: 'adventures-on-gcp'